# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sct-pat-fi',
                'doc_host': 'https://matiasto.github.io',
                'git_url': 'https://github.com/matiasto/sct-pat-fi',
                'lib_path': 'sct_pat_fi'},
  'syms': {'sct_pat_fi.core': {'sct_pat_fi.core.foo': ('core.html#foo', 'sct_pat_fi/core.py')}}}
